#!/bin/bash
echo "Remember to do it on initramfs linux mode or it wont be presistent on next boot!"
sleep 4
clear
bypassFlag=/encryptStorageTrustTool/bypass.flag
if [ ! -f ${bypassFlag} ]; then
echo "Are you sure you want to enable encryption bypass mode?"
echo "WARNING : This will render the OS and the DATA into insecure state"
echo "And you also need to put in the disk password, otherwise the Linux will NOT boot into XNU Mode"
echo "You have been warned!"
echo "==="
echo "To disable bypass mode you need to execute this tool again"
echo "If you change your mind you can put the password to empty to cancel the process"
echo -n "Disk Password: "
read -s password
if [ -z "${password}" ]; then
echo "Cancelled!"
exit
fi
touch ${bypassFlag}
/encryptStorageTrustTool/renewdatahash "${password}"
systemctl stop boothyOS
reboot -f
else
echo "You are already on bypass mode"
echo "Which mean this one is your attempt to disable the bypass"
echo "Shall we continue? Enter your password to disable bypass mode"
echo "and leave it blank if you still want to enable bypass mode"
echo -n "Disk Password: "
read -s password
if [ -z "${password}" ]; then
echo " Cancelled! "
echo "Remember your data is still in insecure state!"
exit
fi
rm ${bypassFlag}
/encryptStorageTrustTool/renewdatahash "${password}"
systemctl stop boothyOS
reboot -f
fi

