#!/bin/bash
#bash /encryptStorageTrustTool/hwhash #this command will be handled with hwhashd to speedup the hashing process
while [ ! -f /tmp/keyHash ]; do
sleep 0.4 #wait for hwhashd to make hwhash
done
#pass=$(gpg -d -q --batch --passphrase "$(cat /tmp/keyHash)" passwordhash.gpg)
pass=$(cat /tmp/keyHash)
#rm -rf /tmp/hwhash #this hash removal will be handled with the hwhashd
#mkdir /veracryptStorageExpose
echo ${pass}
pass="$(uuidgen)" > /dev/null 2>&1


